# Path: src/main/resources/application.yml


# Adding http2 support
server:
  http2:
    enabled: true

spring:
  datasource:
    # development database
    url: jdbc:postgresql://localhost:5432/portfolio
    username: victor
    password: victorMwas1
    #Database to be injected by hosting service
    # url: ${JDBC_DATABASE_URL}
    # username: ${JDBC_DATABASE_USERNAME}
    # password: ${JDBC_DATABASE_PASSWORD}

  # Spring JPA configs
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  #mail sending api
  mail:
    host: smtp.gmail.com
    port: 587
    username: mwangivictor52@gmail.com
    password: ${EMAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          connectionTimeout: 5000
          timeout: 5000
          starttls:
            enable: true
  
  mvc:
    hidden-method:
      filter:
        enabled: true
# Spring actuator configuration
management:
  # Enable spring actuator to be accessible via web
  endpoints:
    web:
      exposure:
        include:
          - "*"